# Generated by Django 4.2.5 on 2023-09-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_paus',
            new_name='guest_can_pause',
        ),
    ]
